; things worth doing typically take time and effort
; 3.2
(define (make-monitored func)
    (let ((count 0))
        (define (how-many-calls?) count)
        (define (reset-count) (set! count 0))
        (define (call-func arg) (begin (set! count (+ 1 count)) (func arg)))
        (define (dispatch arg)
            (cond ((eq? arg 'how-many-calls?) (how-many-calls?))
                  ((eq? arg 'reset-count) (reset-count))
                  (else (call-func arg))))
    dispatch))

(define (try)
    (define s (make-monitored sqrt))
    (display (s 100))
    (newline)
    (display (s 100))
    (newline)
    (display (s 'how-many-calls?))
    (s 'reset-count)
    (newline)
    (display (s 100))
    (newline)
    (display (s 'how-many-calls?))
)
