; things worth doing typically take time and effort.
; 3.23

(define (front-ptr queue) (car queue))
(define (rear-ptr queue) (cdr queue))
(define (set-front-ptr! queue item) (set-car! queue item))
(define (set-rear-ptr! queue item) (set-cdr! queue item))

(define (make-queue) (cons '() '()))

(define (empty-quque? queue) (null? (front-ptr queue)))

(define (only-one-element? queue)
          (and (null? (cdr (front-queue-ptr queue))) (null? (car (rear-queue-ptr queue)))))

(define (front-queue queue)
    (if (empty-quque? queue)
        (error "empty queue")
        (car (front-ptr queue))))

(define (front-queue-ptr queue)
    (if (empty-quque? queue)
        (error "empty queue")
        (cdr (front-ptr queue))))

(define (rear-queue queue)
    (if (empty-quque? queue)
        (error "empty queue")
        (car (rear-ptr queue))))

(define (rear-queue-ptr queue)
    (if (empty-quque? queue)
        (error "empty queue")
        (cdr (rear-ptr queue))))

(define (rear-insert-queue! queue item)
    (let ((new-item (cons item (cons '() '()))))
        (cond ((empty-quque? queue)
                (set-front-ptr! queue new-item)
                (set-rear-ptr! queue new-item)
                queue)
              (else (set-cdr! (rear-queue-ptr queue) new-item)
                    (set-car! (cdr new-item) (rear-ptr queue))
                    (set-rear-ptr! queue new-item)
                    queue))))

(define (front-insert-queue! queue item)
    (let ((new-item (cons item (cons '() '()))))
        (cond ((empty-quque? queue)
                (set-front-ptr! queue new-item)
                (set-rear-ptr! queue new-item)
                queue)
              (else (set-car! (front-queue-ptr queue) new-item)
                    (set-cdr! (cdr new-item) (front-ptr queue))
                    (set-front-ptr! queue new-item)
                    queue))))

(define (front-delete-queue! queue)
    (cond ((empty-quque? queue)
            (error "empty queue"))
          ((only-one-element? queue) (set-front-ptr! queue '()) (set-rear-ptr! queue '()))
          (else
            (set-front-ptr! queue (cdr (front-queue-ptr queue)))
            (set-car! (front-queue-ptr queue) '()))))

(define (rear-delete-queue! queue)
    (cond ((empty-quque? queue)
            (error "empty queue"))
          ((only-one-element? queue) (set-front-ptr! queue '()) (set-rear-ptr! queue '()))
          (else
            (set-rear-ptr! queue (car (rear-queue-ptr queue)))
            (set-cdr! (rear-queue-ptr queue) '()))))

(define (display-queue queue)
    (define (display-iter head)
        (cond ((null? head) (display " "))
              (else (display (car head)) (display-iter (cddr head)))))
    (display-iter (front-ptr queue)))

(define (try)
    (define q1 (make-queue))
    (display-queue q1)
    (newline)
    (rear-insert-queue! q1 'a)
    (display-queue q1)
    (newline)
    (display (only-one-element? q1))
    (newline)
    (rear-insert-queue! q1 'b)
    (display-queue q1)
    (newline)
    (display (only-one-element? q1))
    (newline)
    (front-delete-queue! q1)
    (display-queue q1)
    (newline)
    (front-delete-queue! q1)
    (display-queue q1)
    (newline)
    (front-insert-queue! q1 'a)
    (display-queue q1)
    (newline)
    (front-insert-queue! q1 'b)
    (display-queue q1)
    (newline)
    (front-insert-queue! q1 'c)
    (display-queue q1)
    (newline)
    (front-delete-queue! q1)
    (display-queue q1)
    (newline)
    (rear-delete-queue! q1)
    (display-queue q1)
    (newline)
    (display (only-one-element? q1))
    (newline)
    (rear-delete-queue! q1)
    (display-queue q1)
    (newline)
)

(try)
