(define (compose f g)
	(lambda (x) ((f) ((g) x))))
(define (square)
	(lambda (x) (* x x)))
(define (inc)
	(lambda (x) (+ x 1)))
(define (try)
	((compose square inc) 6))

(define (repeated f n);使用里1.42的函数
	(cond ((= n 1) f)
;		(else ((f) (repeated f (- n 1))))))
		  (else (compose f (repeated f (- n 1))))))
(define (square)
	(lambda (x) (* x x)))
(define (try)
;	(display (((square )square)5))
	((repeated square 2) 5))
