(define (try)
    (newline)
    (display (cons 1 2))
    (newline)
    (display (pair? (cons 1 2)))
    (newline)
    (display (pair? (car (cons 1 2))))
    (newline)
    (display (pair? (cdr (cons 1 2))))
    (newline)
    (display "(list 1 2)")
    (display (list 1 2))
    (newline)
    (display (pair? (list 1 2)))
    (newline)
    (display (pair? (car (list 1 2))))
    (newline)
    (display (pair? (cdr (list 1 2))))
    (display "(list 1)")
    (display (list 1))
    (newline)
    (display (pair? (list 1)))
    (newline)
    (display (pair? (car (list 1))))
    (newline)
    (display (pair? (cdr (list 1))))
)

(try)
