(define (accumulate means f a next b)
	(if (> a b)
		1
	(means (f a) 
		(product f (next a) next b)
	))
)

(define (product f a next b)
	(accumulate * f a next b)
)
;(define (product f a next b)
;	(define (deal c a)
;	(if (> a b)
;		c
;	(deal (* c a) (next a)) 
;	))
;	(deal 1 a)
;)
(define (i x) x)
(define (squre x) (* x x))
(define (squre1 x) 
		(/ (* x x)
			(*(+ x 1) (+ x 1))
		)
)
(define (inc n) (+ n 1))
(define (incby2 n) (+ n 2))
(define (caculatePi b)
;	(/ (product squre 2.0 incby2 (* 2 b))
;	 (product squre 3.0 incby2 (- (* 2 b) 1))
	 (* 2 (product squre1 2.0 incby2  b))
)
	
	
