(define (cont-frac n d k)
	(define (cc i)
	(if (= i k)
		0.0
	(/ (n i) (+ (d i) (cc (+ 1 i))))
	)
;	(display i)	;这个位置不注释掉为什么不可以？
	)
	(cc 1)
)

(define (s f x)
	(let ((xv (f x)))
		(if (< (abs (- x xv)) 0.00001) 
			x
		(s f xv)
		)
	)
)
(define (cacul j)(cond((< j 3) j)
							 ((= (remainder j 3) 2) (* 2 (+ 1 (/ (- j 2) 3))))
							 (else 1))
)
(define (ffe k)
	(+(cont-frac (lambda (j) 1.0) cacul k) 2.0)
)	
