(define (s f x)
	(let ((xv (f x)))
		(if (< (abs (- x xv)) 0.001) 
			x
		(s f xv)
		)
	)
)	
(define (cubic a b c) (lambda (x) (+ (* x x x) (* a x x) (* b x) c)))
(define dx 0.00001)
(define (deriv g)
	(lambda (x) 
		(/ (- (g (+ x dx)) (g x)) dx))
)
(define (newton g y)
	(s (lambda (x) (- x (/ (g x) ((deriv g) x)))) y)
)
(define (sqr y)
	(s (lambda (x) (/ (+ x (/ y x)) 2.0)) 1.0)
)
