(define (searchroot f a b)
	(let ((mid (/ (+ a b) 2.0)))
	;(let ((mid (average a b)))
	(if (< (abs (- a b)) 1)
		mid
		(let ((test (f mid)))
			(cond ((> test 0) (searchroot f a mid))
				  ((< test 0) (searchroot f mid b))
				  (else mid)))
	))

(define (half-method f a b)
	(let ((av (f a))
		  (bv (f b))
		 )
		(cond ((and (> 0 av) (< 0 bv)) 
				(searchroot f a b))
		      ((and (< 0 av) (> 0 bv)) 
				(searchroot f b a))
			  (else 
				(error "Values are not regular" a b))
		)
	)
)
		
