;(define (sum f a next b) 
;	(if (> a b)
;		0
;	(+ (f a)
;		(sum f (next a) next b)
;	)))
;(define (sum f a next b)
;	(define	(sum1 c a b) 
;		(if (> a b)
;			c
;		(sum1 (+ c (f a)) (next a) b)
;		)
;	)
;	(sum1 0 a b)
;)
			
(define (sum f a next b)
	(define	(sum1 c a) 
		(if (> a b)
			c
		(sum1 (+ c (f a)) (next a))
		)
	)
	(sum1 0 a)
)
(define (cube x) (* x x x))
(define (il f a b n)
	;(define (h a b n);错误在于已经声明了a b n,不需要重复
	(define (h)
		(/ (- b a) n))
	(define (next1a a)
		(+ a (h)))
	(define (next2a a)
		(+ a (* 2 (h))))
	(/ (* (h)
		 (+ 
			(sum f a next1a b) 
			(* 2 (sum f (+ a (next1a a)) next2a (- b (next1a a))))
			(sum f (+ a (next1a a)) next1a (- b (next1a a)))
		 )
		) 
	3.0)
)
