(define (sum f a next b) 
	(if (> a b)
		0
	(+ (f a)
		(sum f (next a) next b)
	)))
(define (i x) x)
(define (inc n) (+ n 1))
(define (cube x) (* x x x))
(define (scab a b)
	(sum cube a inc b))
(define (pisum a b);caculate PI
	(define (piterm x)
		(/ 1.0 (* x (+ x 2))))
	(define (pinext x)
		(+ x 4))
	(sum piterm a pinext b)
)
(define (intergral f a b dx)
	(define (nexta a) 
		(+ a dx))
	(* dx (sum f (+ a (/ dx 2.0)) nexta b))
	)
(define (il f a b n);practise 1.30
	(define (h)
		(/ (- b a) n))
	(define (next1a a)
		(+ a (h)))
	(define (next2a a)
		(+ a (* 2 (h))))
	(/ (* (h)
		 (+ (sum f a next1a b) 
			(* 2 (sum f (+ a (next1a a)) next2a (- b (next1a a))))
			(sum f (+ a (next1a a)) next1a (- b (next1a a)))
		 )
		) 
	3.0)
)
