; things worth doiong typically take time and effort
; 3.5
(define (p x y)
    (<= (+ (square (- x 5)) (square (- y 7))) (square 3)))

(define (estimate-integral f x1 x2 y1 y2 trials)
    (define (area x1 x2 y1 y2) (* (abs (- x1 x2)) (abs (- y1 y2))))
    (define (test) (f (random-in-range x1 x2) (random-in-range y1 y2)))
    (define (random-in-range low high) (+ low (random (* 1.0 (- high low)))))
    (* (mente-carlo trials test) (area x1 x2 y1 y2)))
(define (mente-carlo trials test)
    (define (iter left succ)
        (cond ((= left 0) (/ (* 1.0 succ) trials))
              ((test) (iter (- left 1) (+ succ 1)))
              (else (iter (- left 1) succ))))
    (iter trials 0))

(define (try)
    (display (/ (estimate-integral p 2 8 4 10 10) 9))
    (newline)
    (display (/ (estimate-integral p 2 8 4 10 100) 9))
    (newline)
    (display (/ (estimate-integral p 2 8 4 10 1000) 9))
    (newline)
    (display (/ (estimate-integral p 2 8 4 10 10000) 9))
    (newline)
    (display (/ (estimate-integral p 2 8 4 10 100000) 9))
    (newline)
    (display (/ (estimate-integral p 2 8 4 10 100000) 9))
)
(try)
